# Generated by Django 5.0 on 2024-01-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_program_longname_program_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
