# Generated by Django 5.0 on 2024-01-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_program_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
