# Generated by Django 5.0 on 2024-01-02 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_curriculum_created_curriculum_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='effectivity',
        ),
    ]
