# Generated by Django 5.0 on 2024-01-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_curriculum_effectivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='prereq',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
