# Generated by Django 5.0 on 2024-01-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_subjects_prereq'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='subtype',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
