# Generated by Django 5.0 on 2024-01-02 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_subjects_subtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curriculum',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='subjects',
            old_name='description',
            new_name='desc',
        ),
    ]
