# Generated by Django 5.0 on 2024-01-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_description_curriculum_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='major',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
